# Generated by Django 4.2.3 on 2023-09-29 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "github",
                    models.URLField(
                        max_length=500,
                        validators=[
                            django.core.validators.MinLengthValidator(10)
                        ],
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(
                        max_length=500,
                        validators=[
                            django.core.validators.MinLengthValidator(10)
                        ],
                    ),
                ),
                ("bio", models.TextField()),
            ],
        ),
    ]
