# Generated by Django 4.2.3 on 2023-09-30 00:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_rename_keywords_project_keyword"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="Profile",
            new_name="profile",
        ),
    ]
